CREATE TABLE cashback_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      VARCHAR(255)   NOT NULL,
    merchant_name    VARCHAR(255)   NOT NULL,
    product_category VARCHAR(255)   NOT NULL,
    cashback_amount  NUMERIC(19, 2) NOT NULL
);

CREATE INDEX idx_cashback_record_customer_id ON cashback_record (customer_id);
